"""
Podcast digest email builder.

Renders an HTML email containing summaries for one or more new podcast episodes.
"""
from __future__ import annotations

from datetime import datetime, timezone


def render_podcast_digest(episodes: list[dict]) -> tuple[str, str]:
    """
    Build a podcast digest email.

    Args:
        episodes: list of dicts from watcher.check_feeds()

    Returns:
        (subject, html_body) tuple
    """
    date_str = datetime.now(tz=timezone.utc).strftime("%A, %b %-d")
    count = len(episodes)
    subject = f"🎙️ {count} new podcast {'summary' if count == 1 else 'summaries'} — {date_str}"

    sections = "\n".join(_render_episode(ep) for ep in episodes)

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{subject}</title>
<style>
  body {{ margin:0; padding:0; background:#f7fafc; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; color:#2d3748; }}
  .wrapper {{ max-width:640px; margin:32px auto; padding:0 16px; }}
  .header {{ background:#1a1a2e; border-radius:10px 10px 0 0; padding:24px 28px; }}
  .header h1 {{ margin:0; color:#fff; font-size:22px; font-weight:800; }}
  .header p  {{ margin:6px 0 0; color:#a0c4ff; font-size:14px; }}
  .episode {{ background:#fff; border:1px solid #e2e8f0; border-radius:10px; padding:24px 28px; margin:16px 0; }}
  .ep-meta  {{ font-size:12px; color:#a0aec0; margin:0 0 16px; }}
  .ep-podcast {{ font-weight:700; color:#3182ce; }}
  h2 {{ margin:0 0 4px; font-size:20px; color:#1a202c; }}
  h3 {{ margin:20px 0 8px; font-size:13px; font-weight:700; text-transform:uppercase; letter-spacing:.5px; color:#718096; }}
  .tldr {{ font-size:15px; line-height:1.7; color:#4a5568; margin:0; }}
  .tags {{ display:flex; flex-wrap:wrap; gap:6px; margin:0; padding:0; list-style:none; }}
  .tag {{ background:#ebf8ff; color:#2b6cb0; font-size:12px; font-weight:600; padding:3px 10px; border-radius:20px; }}
  .quote {{ border-left:3px solid #3182ce; padding:10px 14px; background:#f7fafc; border-radius:0 6px 6px 0; margin:8px 0; }}
  .quote p {{ margin:0 0 4px; font-style:italic; color:#2d3748; font-size:14px; line-height:1.6; }}
  .quote cite {{ font-size:12px; color:#718096; }}
  .actions {{ margin:0; padding:0 0 0 18px; }}
  .actions li {{ font-size:14px; color:#4a5568; margin:4px 0; }}
  .footer {{ text-align:center; font-size:12px; color:#a0aec0; padding:20px 0 32px; }}
</style>
</head>
<body>
<div class="wrapper">
  <div class="header">
    <h1>🎙️ Podcast Digest</h1>
    <p>{date_str} &mdash; {count} new episode{'s' if count != 1 else ''}</p>
  </div>
  {sections}
  <div class="footer">
    <p>Generated by Daily Bulletin &mdash; Podcast Summarizer</p>
  </div>
</div>
</body>
</html>"""

    return subject, html


def _render_episode(ep: dict) -> str:
    s = ep.get("summary", {})
    podcast = ep.get("podcast_title", "")
    title = ep.get("episode_title", "Unknown Episode")
    published = ep.get("published", "")
    tldr = s.get("tldr", "")

    topics_html = "".join(
        f'<li class="tag">{_esc(t)}</li>' for t in s.get("key_topics", [])
    )

    quotes_html = "".join(
        f"""<div class="quote">
          <p>"{_esc(q.get('quote',''))}"</p>
          {f'<cite>{_esc(q.get("context",""))}</cite>' if q.get("context") else ""}
        </div>"""
        for q in s.get("notable_quotes", [])
    )

    actions_html = "".join(
        f"<li>{_esc(a)}</li>" for a in s.get("action_items", [])
    )

    audio_btn = (
        f'<p style="margin:16px 0 0"><a href="{_esc(ep["audio_url"])}" '
        f'style="background:#3182ce;color:#fff;padding:8px 16px;border-radius:6px;'
        f'font-size:13px;font-weight:600;text-decoration:none;">▶ Listen</a></p>'
        if ep.get("audio_url") else ""
    )

    return f"""<div class="episode">
  <p class="ep-meta">
    <span class="ep-podcast">{_esc(podcast)}</span>
    {f'&nbsp;&middot;&nbsp;{_esc(published)}' if published else ''}
  </p>
  <h2>{_esc(title)}</h2>

  <h3>TL;DR</h3>
  <p class="tldr">{_esc(tldr)}</p>

  {'<h3>Key Topics</h3><ul class="tags">' + topics_html + '</ul>' if topics_html else ''}

  {'<h3>Notable Quotes</h3>' + quotes_html if quotes_html else ''}

  {'<h3>Action Items</h3><ul class="actions">' + actions_html + '</ul>' if actions_html else ''}

  {audio_btn}
</div>"""


def _esc(s: object) -> str:
    return (
        str(s)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )
